### ISSUE TITLE
403 errors are swallowed by fetch tool POST

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-storage#100]
The asset server is configured to return a JSON body along with a 403, but this line of code is ignoring the fact that you can get both a response AND not be successful https://github.com/LLK/scratch-storage/blob/develop/src/FetchTool.js#L45

We should be rejecting that promise chain on 403s, but because of the way the fetch tool returns just the text response and not the status, and does not reject the response itself, there is no way for the promise chain to fail. 

/cc @cwillisf @BryceLTaylor @kchadha this is the reason that you do not get the "project failed to save" when you get authentication gets bumped by signing in to another computer. You can clearly see the 403s when you try to save, but they are being swallowed, and since nothing actually uses the response body we aren't catching the error elsewhere.

**Comment by cwillisf** [comment]
Nice find! I would consider this critical since it can cause data loss. It seems like you could even have individual assets that don't get saved but do get marked "clean" in the client such that the project stays broken even if you fix the sign-in problem.

**Comment by paulkaplan** [comment]
@cwillisf would the correct fix for this just to check the status code and throw unless it is a 200? That linked PR to GUI is probably not the best because it ties saving success to a specific JSON response from the server (`status: ok`) where it would be better to use the universal language of http status codes instead. My only reservation is exactly what status codes we should use for POST responses, whether it is any 2XX, or specifically 200s. @rschamp any thoughts?

**Comment by rschamp** [comment]
@paulkaplan I think you're right that it should probably act the same way as the nets tool which throws unless the status is 2XX: https://github.com/LLK/scratch-storage/blob/develop/src/NetsTool.js#L63

**Comment by paulkaplan** [comment]
Aha! Alright that sounds good.

**Comment by sheeeeep** [comment]
It seems like all occasion with fetch would exist similar problems ? For example, I have a costume asset that 404 in first source and 200 in second source. Because of fetch resolve when 404, this asset is unable to download.

**Comment by benjiwheeler** [comment]
There are many places in our code where I worry we're not handling the result of every promise resolution/rejection or response body that might occur. It might make sense to do some kind of audit or search for these. I remember seeing other instances in gui code that handles storage, though I can't find open issues for that.
