### ISSUE TITLE
Replace `crypto`

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-storage#18]
`crypto` is a node built-in module that does not work on the browser (it uses `Buffer` objects, but only typed arrays are available in the browser, and they are not equivalent). 

We need a module that works on the browser also for computing md5s

**Comment by thisandagain** [comment]
@paulkaplan Do you want to take this one? I presume switching to something like https://www.npmjs.com/package/md5 should be fairly straightforward?
