### ISSUE TITLE
CE-144 Suggestion: Don't store useragent strings within the project.json

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-storage#394]
On projects.scratch.mit.edu/xxxxxxxx/, at the end of a JSON, you can see one's useragent string, which I believe is an unnecessary invasion of Scratchers' privacy.
My suggestion is to make future projects' JSON not include one's full useragent string.

Note: The project ID was intentionally censored to protect Scratcher privacy.

Another note: If this is not possible for any reason, feel free to reject or only partially implement my suggestion.

Yet another note (sorry if this is annoying): The reason why I never post on the fourms is because I am not allowed to. Please don't ask about this one.

**Comment by benjiwheeler** [comment]
We discussed this in the engineering team and agreed that this information is no longer useful or used, and that it should be OK to remove.

**Comment by PPPDUD** [comment]
Great. Any progress on removing it in future projects?

**Comment by cwillisf** [comment]
We've added this to our task list for future work. Thanks for bringing this to our attention!

**Comment by PPPDUD** [comment]
Great! Thanks!
